const db = require('./index');

const TYPES = ['transfer', 'purchase_order', 'alert'];
const STATUSES = ['pending', 'approved', 'rejected'];

// Convert stored JSON strings into JavaScript objects.
function parse(row) {
  if (!row) return null;

  return {
    ...row,
    details: row.details ? JSON.parse(row.details) : {},
    evidence: row.evidence ? JSON.parse(row.evidence) : {},
  };
}

// Create a new suggested action.
function createAction({
  type,
  sku,
  details,
  evidence,
  explanation = null
}) {
  if (!TYPES.includes(type)) {
    throw new Error(`Invalid action type: ${type}`);
  }

  if (typeof sku !== 'string' || !sku) {
    throw new Error('sku is required');
  }

  if (typeof details !== 'object' || details === null || Array.isArray(details)) {
    throw new Error('details must be an object');
  }

  if (typeof evidence !== 'object' || evidence === null || Array.isArray(evidence)) {
    throw new Error('evidence must be an object');
  }

  const info = db
    .prepare(
      'INSERT INTO actions (type, sku, details, evidence, explanation) VALUES (?, ?, ?, ?, ?)'
    )
    .run(
      type,
      sku,
      JSON.stringify(details),
      JSON.stringify(evidence),
      explanation
    );

  return getAction(info.lastInsertRowid);
}

// Retrieve one action by its ID.
function getAction(id) {
  return parse(
    db.prepare('SELECT * FROM actions WHERE id = ?').get(id)
  );
}

// List all actions, or filter by status.
function listActions(status) {
  const rows = status
    ? db.prepare(
        'SELECT * FROM actions WHERE status = ? ORDER BY id DESC'
      ).all(status)
    : db.prepare(
        'SELECT * FROM actions ORDER BY id DESC'
      ).all();

  return rows.map(parse);
}

// Change an action's status.
function setStatus(id, status) {
  if (!STATUSES.includes(status)) {
    throw new Error(`Invalid status: ${status}`);
  }

  db.prepare(
    'UPDATE actions SET status = ? WHERE id = ?'
  ).run(status, id);

  return getAction(id);
}

// Save an explanation generated by the AI.
function setExplanation(id, text) {
  db.prepare(
    'UPDATE actions SET explanation = ? WHERE id = ?'
  ).run(text, id);

  return getAction(id);
}

// Remove old pending suggestions before a new analysis run.
function clearPendingActions() {
  db.prepare(
    "DELETE FROM actions WHERE status = 'pending'"
  ).run();
}

module.exports = {
  createAction,
  getAction,
  listActions,
  setStatus,
  setExplanation,
  clearPendingActions,
  TYPES,
  STATUSES,
};