
module.exports = {
  COVER_DAYS: 14,
  DEFAULT_LEAD_DAYS: 7,

  TRANSFER_DAYS: 1,
  TRANSFER_COST_PER_UNIT: 5,
  DONOR_KEEP_DAYS: 14,
  MIN_COVER_AFTER_FIX: 7,

  LOST_SALE_MARKUP: 1.3,
  OVERDUE_RISK_COVER_DAYS: 7,

  MIN_UNITS_FOR_TREND: 10,
  SPIKE_RATIO: 2,
  DROP_RATIO: 0.5,

  SLOW_COVER_DAYS: 120,
  SLOW_KEEP_DAYS: 90,
  SLOW_MIN_VALUE: 10000,
  CLEARANCE_RECOVERY: 0.7,

  DECIDED_MEMORY_HOURS: 24
};